name: action1
env:
  APPLICATION_NAME: "MYFLASK"
  PACKAGE_NAME    : "ABOBUS_ver_${{ github.sha }}"
on:
  push:
    branches:
      - main
      
jobs: 
  my_testing:
    runs-on: ubuntu-latest
  
    steps: 
    - name: Print Hello Message
      run:  echo "Hello world from testing"
      
    - name: Execute few commands
      run : |
        echo "app is ${{ env.APPLICATION_NAME}}"
  
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    steps: 
    - name: Print Hello Message
      run:  echo "Hello world from deploy"
    
    - name: Printing Deployment package
      run: echo "$ paketik eto {{ env.PACKAGE_NAME}}"
